/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/euratlhon/ADIS-16480-Interface/src/adis_16480_driver/msg/Acceleration.msg
 *
 */


#ifndef ADIS_16480_DRIVER_MESSAGE_ACCELERATION_H
#define ADIS_16480_DRIVER_MESSAGE_ACCELERATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adis_16480_driver
{
template <class ContainerAllocator>
struct Acceleration_
{
  typedef Acceleration_<ContainerAllocator> Type;

  Acceleration_()
    : linear_x(0)
    , linear_y(0)
    , linear_z(0)  {
    }
  Acceleration_(const ContainerAllocator& _alloc)
    : linear_x(0)
    , linear_y(0)
    , linear_z(0)  {
    }



   typedef int64_t _linear_x_type;
  _linear_x_type linear_x;

   typedef int64_t _linear_y_type;
  _linear_y_type linear_y;

   typedef int64_t _linear_z_type;
  _linear_z_type linear_z;




  typedef boost::shared_ptr< ::adis_16480_driver::Acceleration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adis_16480_driver::Acceleration_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Acceleration_

typedef ::adis_16480_driver::Acceleration_<std::allocator<void> > Acceleration;

typedef boost::shared_ptr< ::adis_16480_driver::Acceleration > AccelerationPtr;
typedef boost::shared_ptr< ::adis_16480_driver::Acceleration const> AccelerationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adis_16480_driver::Acceleration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adis_16480_driver::Acceleration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace adis_16480_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'adis_16480_driver': ['/home/euratlhon/ADIS-16480-Interface/src/adis_16480_driver/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adis_16480_driver::Acceleration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adis_16480_driver::Acceleration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adis_16480_driver::Acceleration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94eeddc045d72757ec70cb9721a889c2";
  }

  static const char* value(const ::adis_16480_driver::Acceleration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94eeddc045d72757ULL;
  static const uint64_t static_value2 = 0xec70cb9721a889c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adis_16480_driver/Acceleration";
  }

  static const char* value(const ::adis_16480_driver::Acceleration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 linear_x\n\
int64 linear_y\n\
int64 linear_z\n\
";
  }

  static const char* value(const ::adis_16480_driver::Acceleration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_x);
      stream.next(m.linear_y);
      stream.next(m.linear_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Acceleration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adis_16480_driver::Acceleration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adis_16480_driver::Acceleration_<ContainerAllocator>& v)
  {
    s << indent << "linear_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.linear_x);
    s << indent << "linear_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.linear_y);
    s << indent << "linear_z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.linear_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADIS_16480_DRIVER_MESSAGE_ACCELERATION_H
