/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/euratlhon/ADIS-16480-Interface/src/adis_16480_driver/srv/switchDataOutMode.srv
 *
 */


#ifndef ADIS_16480_DRIVER_MESSAGE_SWITCHDATAOUTMODE_H
#define ADIS_16480_DRIVER_MESSAGE_SWITCHDATAOUTMODE_H

#include <ros/service_traits.h>


#include <adis_16480_driver/switchDataOutModeRequest.h>
#include <adis_16480_driver/switchDataOutModeResponse.h>


namespace adis_16480_driver
{

struct switchDataOutMode
{

typedef switchDataOutModeRequest Request;
typedef switchDataOutModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct switchDataOutMode
} // namespace adis_16480_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::adis_16480_driver::switchDataOutMode > {
  static const char* value()
  {
    return "6f0dbb184a0bef2ecba0759c5677b170";
  }

  static const char* value(const ::adis_16480_driver::switchDataOutMode&) { return value(); }
};

template<>
struct DataType< ::adis_16480_driver::switchDataOutMode > {
  static const char* value()
  {
    return "adis_16480_driver/switchDataOutMode";
  }

  static const char* value(const ::adis_16480_driver::switchDataOutMode&) { return value(); }
};


// service_traits::MD5Sum< ::adis_16480_driver::switchDataOutModeRequest> should match 
// service_traits::MD5Sum< ::adis_16480_driver::switchDataOutMode > 
template<>
struct MD5Sum< ::adis_16480_driver::switchDataOutModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::adis_16480_driver::switchDataOutMode >::value();
  }
  static const char* value(const ::adis_16480_driver::switchDataOutModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::adis_16480_driver::switchDataOutModeRequest> should match 
// service_traits::DataType< ::adis_16480_driver::switchDataOutMode > 
template<>
struct DataType< ::adis_16480_driver::switchDataOutModeRequest>
{
  static const char* value()
  {
    return DataType< ::adis_16480_driver::switchDataOutMode >::value();
  }
  static const char* value(const ::adis_16480_driver::switchDataOutModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::adis_16480_driver::switchDataOutModeResponse> should match 
// service_traits::MD5Sum< ::adis_16480_driver::switchDataOutMode > 
template<>
struct MD5Sum< ::adis_16480_driver::switchDataOutModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::adis_16480_driver::switchDataOutMode >::value();
  }
  static const char* value(const ::adis_16480_driver::switchDataOutModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::adis_16480_driver::switchDataOutModeResponse> should match 
// service_traits::DataType< ::adis_16480_driver::switchDataOutMode > 
template<>
struct DataType< ::adis_16480_driver::switchDataOutModeResponse>
{
  static const char* value()
  {
    return DataType< ::adis_16480_driver::switchDataOutMode >::value();
  }
  static const char* value(const ::adis_16480_driver::switchDataOutModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADIS_16480_DRIVER_MESSAGE_SWITCHDATAOUTMODE_H
